cd pretrained-model
echo Concatenating model files...
cat imagenet.part* > imagenet.tar.gz
echo Extracting archive...
tar -xzf imagenet.tar.gz
echo Removing intermediate files...
rm imagenet.tar.gz
echo Done.
